//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMAGE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class film_country
    {
        public film_country()
        {
            this.Filmcountry = new HashSet<Filmcountry>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Filmcountry> Filmcountry { get; set; }
    }
}
