//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMAGE2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KINOEntities6 : DbContext
    {
        public KINOEntities6()
            : base("name=KINOEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<film_country> film_country { get; set; }
        public DbSet<film_genre> film_genre { get; set; }
        public DbSet<Filmcountry> Filmcountry { get; set; }
        public DbSet<Filmgenre> Filmgenre { get; set; }
        public DbSet<Proba_film> Proba_film { get; set; }
    }
}
