//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMAGE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proba_film
    {
        public Proba_film()
        {
            this.Filmcountry = new HashSet<Filmcountry>();
            this.Filmgenre = new HashSet<Filmgenre>();
        }
    
        public int id_film { get; set; }
        public string name_film { get; set; }
        public Nullable<int> year_film { get; set; }
        public string description_film { get; set; }
        public string image_film { get; set; }
    
        public virtual ICollection<Filmcountry> Filmcountry { get; set; }
        public virtual ICollection<Filmgenre> Filmgenre { get; set; }
    }
}
